### ISSUE TITLE
Question: What type of format is the data in?

### ISSUE THREAD

**Issue by bhairavmehta95** [setiQuest/ML4SETI#2]
Not sure if this is already out, but I was hoping to see a few samples of data. Is it just images, or is there another format of the data (i.e CSV)?

**Comment by gadamc** [comment]
The data will come in complex-valued time-series data, just like the "archive compamp" files from the SETI@IBMCloud project. From there you can pre-process the data, produce spectrograms, images and then apply classification. We are considering (likely) to provide the data already pre-processed as images, which will certainly be useful for initial testing and focus on machine learning parts. However, be aware that there may be signal processing techniques with the time-series data that can ultimately improve the classification.
