### ISSUE TITLE
 ImportError: No module named 'dsp'  while installing ibmseti

### ISSUE THREAD

**Issue by bsaldivaremc2** [setiQuest/ML4SETI#5]
Best regards. I am using IBM Data science experience. Following the step:
`!pip install --user --upgrade ibmseti`
I get the error:
`Collecting ibmseti
  Downloading ibmseti-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/sf2e-5e1a2375405816-049fa5141c14/pip-build/ibmseti/setup.py", line 25, in <module>
        from ibmseti.__info__ import __version__
      File "/tmp/sf2e-5e1a2375405816-049fa5141c14/pip-build/ibmseti/ibmseti/__init__.py", line 18, in <module>
        import dsp
    ImportError: No module named 'dsp'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/sf2e-5e1a2375405816-049fa5141c14/pip-build/ibmseti/`

I am using notebook with python 3.5

**Comment by kylebuckingham** [comment]
it only works on python 2.7 (in my experience)

**Comment by bsaldivaremc2** [comment]
Indeed. It worked on python 2.7.

**Comment by gadamc** [comment]
Thanks guys -- I haven't had time to update the setup scripts to make `ibmseti` work with python 3.
